# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: auth0extensions/ci-node:latest

jobs:
  test:
    <<: *defaults
    environment:
      CC_TEST_REPORTER_ID: 28feed842eb696f91787e9675e46db4a56a76b126c40ad884829a36a76385c6f

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-dependencies-

      - run: npm install

      # - run:
      #   name: FOSSA Init
      #   command: fossa init
      # - run:
      #     name: FOSSA Analyze
      #     command: fossa analyze
      # - run:
      #     name: FOSSA Test
      #     command: fossa test

      # code climate requires before-build and after-build to be executed around test
      - run:
          name: Run Tests
          command: |
            #./cc-test-reporter before-build
            npm run test
            #./cc-test-reporter after-build --exit-code $?
      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test:
    jobs:
      - test
  test_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
